### ISSUE TITLE
ValidationError with cloudformation template

### ISSUE THREAD

**Issue by sravinet** [velomash/aws-git-backed-gatsby-static-site#1]
Dear Adam, thank you for this project. I trust it will be very useful but unfortunately I'm stuck so far.

```
npm run create-stack

> aws-git-backed-gatsby-static-site@0.8.2 create-stack /Users/sylvan/Writing/aws-git-backed-gatsby-static-site
> export $(cat config.env | xargs) && ./bin/create.sh

An error occurred (ValidationError) when calling the CreateStack operation: Template format error: Unrecognized resource types: [AWS::CodeBuild::Project]
Creating the example-stack-name stack...
```

[more npm blurp edited]

Even spending several hours trying to hunt this issue down (while learning about CloudFormation). When running : 
```
aws --profile XXX cloudformation validate-template --template-body file://./cloudformation.yaml

An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Unrecognized resource types: [AWS::CodeBuild::Project]
```

Did not manage to hunt down the problem, as [AWS::CodeBuild::Project is a valid AWS resource type](https://docs.aws.amazon.com/fr_fr/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html).

You might have more luck?

**Comment by velomash** [comment]
Hey @sravinet !

Thanks for opening an issue. I'm happy to help hunt down your problem.

Unfortunately, CodeBuild inside of CodePipelines will only work in certain regions. Please try the create-stack command in the us-east-1 region.

You can change your cli region with the [configure command](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html)

Let me know how that works out. I'll update the docs to let people know about this restriction.
